apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: monitoring
spec:
  storageClassName: ufs-nfsv4-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
