apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ufs-nfsv4-storage
provisioner: UFS-RSSD-Provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
mountOptions:
  - nolock
  - nfsvers=4.0
