{
 "title": "Pod Start Time",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "pod_created -> pod_scheduled",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{job=\"kubernetes-pods\",pod=~\"myweb-.*\"} - on(job, pod) kube_pod_created{job=\"kubernetes-pods\",pod=~\"myweb-.*\"}  ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "pod_scheduled -> pod_start ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_start_time{job=\"kubernetes-pods\",pod=~\"myweb-.*\"} - on(job, pod) kube_pod_status_scheduled_time{job=\"kubernetes-pods\",pod=~\"myweb-.*\"}  ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "POD 启动时间(pod创建，调度，拉取镜像，pod内容器完全启动)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_state_started{job=\"kubernetes-pods\",pod=~\"myweb-.*\"} - on(job, pod) kube_pod_status_scheduled_time{job=\"kubernetes-pods\",pod=~\"myweb-.*\"}  ",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}