apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ufs-nfsv4-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ucloud/ufsprovisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
mountOptions:
  - nolock
  - nfsvers=4.0
