apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 10
  selector:
    app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: uhub.service.ucloud.cn/ucloud/jenkins:2.222.3 
          ports:
          - containerPort: 8080
          readinessProbe:
            exec:
              command:
              - "env"
          env:
          - name: MYSQL_SERVICE_HOST
            value: 'mysql'
          - name: MYSQL_SERVICE_PORT
            value: '3306'
